#define FEED_MOTOR_STEPS_PER_REVOLUTION 4000 
#define FEED_MOTOR_SHAFT_DIAMETER 30.4
#define FEED_MOTOR_STEPS_PER_MILIMETER 41.88   //FEED_MOTOR_STEPS_PER_REVOLUTION / FEED_MOTOR_SHAFT_DIAMETER * PI

#define BEND_MOTOR_SHAFT_DIAMETER 10
#define BEND_MOTOR_SHOULDER 50
#define BEND_MOTOR_STEPS_PER_REVOLUTION 4000 
#define BEND_MOTOR_STEPS_PER_DEGREE 33.33    //FEED_MOTOR_STEPS_PER_REVOLUTION / 360

#define WIRE_THICKNESS 3


#define CMD_STOP 127
#define CMD_FEED 126
#define CMD_2D_BEND 125
#define CMD_3D_BEND 124

